spring.application.name=lektion-7
spring.datasource.url=jdbc:postgresql://db.twphkaraxwatmcgveefi.supabase.co:5432/postgres?user=postgres&password=Johanhammerin123
spring.datasource.username=<USERNAME>
spring.datasource.password=<PASSWORD>
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
